/**
 * Autogenerated by RTP (based on Thrift) Compiler (1.10.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zhgd.ucc;

import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.async.AsyncPushMethodCallback;
import com.cetc28.rtp.meta_data.AFile;

public class UCCalThriftInterfaceServiceAsyncImpl implements UCCalThriftInterface.AsyncIface {

  public void UCCal_ReceiveCmd(final String stringCmd, final String stringAccess, final AsyncMethodCallback<Integer> resultHandler) throws TException {
    // TODO your implemention goes here!
  }

  public void UCCal_ReadIDCardInfo(final String stringID, final AsyncMethodCallback<Map<String,String>> resultHandler) throws TException {
    // TODO your implemention goes here!
  }

}
