/**
 * Autogenerated by RTP (based on Thrift) Compiler (1.10.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zhgd.ucc;

import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cetc28.rtp.meta_data.AFile;

public class UCCalThriftInterfaceServiceImpl implements UCCalThriftInterface.Iface {

  public int UCCal_ReceiveCmd(String stringCmd, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return 0;
  }

  public Map<String,String> UCCal_ReadIDCardInfo(String stringID) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return null;
  }

}
