/**
 * Autogenerated by RTP (based on Thrift) Compiler (1.10.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zhgd.zxc;

import java.util.List;
import java.util.Map;

public class DMIThriftInterfaceServiceImpl implements DMIThriftInterface.Iface {

  public List<String> DMI_GetAllResId(String stringType, String stringTag, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return null;
  }

  public List<String> DMI_GetDataAttribute(String stringType, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return null;
  }

  public Map<Integer,Map<String,String>> DMI_FilterParam(String stringType, List<String> vecTags, Map<String,List<String>> mpCondition, String stringQyCondition, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return null;
  }

  public Map<String,Map<String,String>> DMI_FilterParam2(String stringType, List<String> vecTags, Map<String,List<String>> mpCondition, String stringQyCondition, String stringAccess, String stringKeyMacro) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return null;
  }

  public int DMI_UpdateData(String stringType, Map<String,Map<String,String>> mpTag2Value, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return 0;
  }

  public int DMI_DeleteData(String stringType, Map<String,List<String>> mpCondition, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return 0;
  }

  public void DMI_DeleteData2(String stringType, List<String> vcId, String stringAccess, String stringKeyMacro) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return ;
  }

  public int DMI_ReceiveCmd(String stringCmd, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return 0;
  }

  public String DMI_TransBegin(String stringType, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return null;
  }

  public int DMI_TransCommit(String stringType, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return 0;
  }

  public int DMI_TransRollback(String stringType, String stringAccess) throws org.apache.thrift.TException { 
    // TODO your implemention goes here!
    return 0;
  }

}
